<?php
// This file generated by Propel 1.6.2 convert-conf target
// from XML runtime conf file /var/www/tarefa/application/scripts/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'tarefa' => 
    array (
      'adapter' => 'pgsql',
      'connection' => 
      array (
        // Desenvolvimento (BICUDA)
        //'dsn' => 'pgsql:host=192.168.22.5 port=5432 dbname=tarefa user=user_tarefa password=senha123'

        // Desenvolvimento novo (ABRAMITES)
        'dsn' => 'pgsql:host=192.168.22.26 port=5432 dbname=tarefa user=user_tarefa password=senha123'

        // Produ��o (JAU)
//        'dsn' => 'pgsql:host=192.168.22.14 port=11999 dbname=tarefa user=user_tarefa password=senha123'
      ),
    ),
    'default' => 'tarefa',
  ),
  'log' => 
  array (
    'type' => 'file',
    'name' => '/var/www/tarefa/tmp/logs/propel.log',
    'ident' => 'propel',
    'level' => '2',
    'conf' => '',
  ),
  'generator_version' => '1.6.2',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'base-classmap.php');
return $conf;