<script>
    $(document).ready(function() {

        // Desabilita o botão 'salvar'.
        $('#submit').attr('disabled', 'disabled');

        $("#salvar").mouseenter(function(){
            var no_tipo_versao = $('#no_tipo_versao').val();
            var co_tipo_versao = $('#co_tipo_versao').val();

            if(co_tipo_versao !== ""){
                if(no_tipo_versao === ""){
                    $('#no_tv_vazio').show();
                    $('#erro').show();
                }else{
                    $('#no_tv_vazio').hide();
                    $('#erro').hide();

                    $.post('/manutencao/tipo-versao/validar/', {no_tipo_versao: no_tipo_versao, co_tipo_versao: co_tipo_versao}, function(data){

                        if(data === 'true'){
                            $('#submit').removeAttr('disabled');
                        }else{
                            $('#submit').attr('disabled', 'disabled');
                        }
                    });
                }
            }else{

                if(no_tipo_versao === "") {

                    $('#submit').attr('disabled', 'disabled');
                    $('#no_tv_vazio').show();
                    $('#erro').show();

                }else{

                    $('#no_tv_vazio').hide();
                    $.post('/manutencao/tipo-versao/validar-no-tipo-versao/', {no_tipo_versao: no_tipo_versao}, function (data) {

                        if (data === 'true') {
                            $('#submit').removeAttr('disabled');
                            $('#no_tv_usado').hide();
                            $('#erro').hide();
                        } else {
                            $('#submit').attr('disabled', 'disabled');
                            $('#no_tv_usado').show();
                            $('#erro').show();
                        }
                    });

                }
            }
        });


    });
</script>
<style>
form label.error{ 
	text-align: right;
	width: 100%;
}
form label.error {
    color: red;
    font-style: italic;
    font-size: 0.9em;
    margin-top: -10px;
}



input {
    border: 1px solid black;
}
input.checkbox {
    border: medium none;
}
input:focus {
    border: 1px dotted black;
}
input.error {
    border: 1px dotted red;
}
</style>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="" class="tip-bottom" data-original-title="Principal"><i class="icon-home"></i>Principal</a>
        -> 
        <a href="/manutencao/tipo-versao/listar" class="tip-bottom" data-original-title="" title="">Tipo de Versões</a>
         -> Cadastro de Tipo de Versões
    </div>
    <h1>Cadastro de Tipo de Versões </h1>
</div>

<div class="content-box cadProf" id="boxGrid"><!-- Start Content Box GRID -->				
    <div class="content-box-content">					
        <div id="cadProf" class="tab-content default-tab"> <!-- INICIO TAB 1-->																												
            <?php echo  $this->mensagem(); ?>
            
                <form action="/manutencao/tipo-versao/adicionar" method="post" class="formValidate" id="form-usuario">
                   	<input type="hidden" value="<?php print $this->aObjTipoVersao->getCoSeqTipoVersao()?>" name="co_tipo_versao" id="co_tipo_versao" />
                    <div class="dados">
                        <div class="linha">
                            <div class="campos">
                                <div class="label">
                                    Nome 
                                </div> 
                                <div>
                                    <input id="no_tipo_versao" name="no_tipo_versao" type="text" class="span3" value="<?php echo $this->noVersao; ?>" />
                                </div>
                                
                                <!-- Mensagem dizendo que o nome do projeto já está em uso. -->
                                <div id="no_tv_usado" style="width: 300px; display: none; color: red; position: absolute; top: 50px; left: 120px">
                                    <em>Este nome já está em uso.</em>
                                </div>

                                <!-- Mensagem dizendo que o campo para o nome do projeto está vazio. -->
                                <div id="no_tv_vazio" style="width: 300px; display: none; color: red; position: absolute; top: 50px; left: 120px">
                                    <em>Este campo é obrigatório.</em>
                                </div>
                            </div>
                        </div>
                        <br />
                        <br />
                            <!--<a href="/manutencao/tipo-versao/listar" class="tip-bottom" data-original-title="" title=""> <input class="button_blue" value="Voltar" type="button" /></a>
                                <input class="button_blue" value="Salvar" type="submit" /> -->
                    </div>

                    <!-- Mensagem informando um erro no formulário. -->
                    <div id="erro" style="width: 500px; display: none; color: red">
                        <em>Um erro ocorreu no preenchimento de algum campo do formulário.</em>
                    </div>

                    <div class="row-fluid">
                        <div class="span12" id="salvar">
                            <div class="form-actions">
                                <button id="submit" class="btn btn-primary" type="submit">Salvar</button>
                                <a href="/manutencao/tipo-versao/listar/num_linhas/<?php echo $this->num_linhas; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/coluna/<?php echo $this->coluna; ?>/ordem/<?php echo $this->ordem; ?>/pg/<?php echo $this->pg; ?>" class="btn" data-original-title="" title="">Voltar</a>
                            </div>	
                        </div>
	</div>
                </form>
            
            <div class="clear"></div><!-- End .clear -->																														
        </div> 
        <!-- End #tab1 --> 	
        <div id="listaProf" class="tab-content">
            <!-- Inicio tab 2 -->
            <!-- TAB LISTA DE PROFISSIONAL -->																													
        </div> 
        <!-- End #tab2 -->			
    </div> <!-- End .content-box-content -->				
</div> <!-- End BOX GERAL GRID--> 
<!-- END BOX CRUD --> 
