<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8" >
<head>
    <title>Suporte e-Sus</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="/css/fullcalendar.css" />
    <link rel="stylesheet" href="/css/maruti-style.css" />
    <link rel="stylesheet" href="/css/maruti-media.css" class="skin-color" />
    
    <script src="/js/excanvas.min.js"></script> 
    <script src="/js/jquery.min.js"></script> 
    <script src="/js/jquery.ui.custom.js"></script> 
    <script src="/js/bootstrap.min.js"></script> 
    <script src="/js/maruti.js"></script> 
    <script src="/js/select2.min.js"></script>
    <script src="/js/jquery.tablesorter.js"></script>
    <script src="/js/jquery.tablesorter.pager.js"></script>
</head>
<body>
<!--Header-part-->
<div id="header"></div>
<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">   
  <ul class="nav">     
    <?php if (Zend_Auth::getInstance()->getIdentity()) { ?>  
        <li class="" >
            <a title="" href="#">
                <i class="icon icon-user"></i> 
                <span class="text">Meu Perfil</span></a>
        </li>
        <li class="">     
            <a title="" href="/acesso/login/sair">
                <i class="icon icon-share-alt"></i> 
                <span class="text">Sair</span></a>
        </li>
    <?php } ?>
  </ul>
</div>
<div id="sidebar">
    <?php
        echo MenuPeer::getHtmlMenu();
    ?>   
</div>
<div id="content">
    <?php echo $this->layout()->content; ?>
</div>
</div>
</div>
<div class="row-fluid">
  <div id="footer" class="span12">Ministério da Saúde - DATASUS-RJ <?php echo VERSAO_SISTEMA; ?></div>
</div>
<script type="text/javascript">
    // This function is called from the pop-up menus to transfer to
    // a different page. Ignore if the value returned is a null string:
    function goPage (newURL) {

        // if url is empty, skip the menu dividers and reset the menu selection to default
        if (newURL != "") {

            // if url is "-", it is this page -- reset the menu:
            if (newURL == "-" ) {
                resetMenu();            
            } 
            // else, send page to designated URL            
            else {  
              document.location.href = newURL;
            }
        }
    }
    // resets the menu selection upon entry to this page:
    function resetMenu() {
       document.gomenu.selector.selectedIndex = 2;
    }
</script>
</body>
</html>
