<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="imagetoolbar" content="no" />
        <title>Extranet</title>
        <link media="screen" rel="stylesheet" type="text/css" href="/css/admin-login.css"  />        
        <!--[if lte IE 6]><link media="screen" rel="stylesheet" type="text/css" href="/css/admin-login-ie.css" /><![endif]-->
        <link type="text/css" href="/css/jquery-ui.css" rel="stylesheet" />
        <style type="text/css">

            .forms {
                float: left;
/*                width: 620px;*/
            }

            .general_form {
                font-size: 13px;
                line-height: 24px;
            }

            .general_form .row {
                width: 100%;
                overflow: hidden;
                padding: 0 0 11px;
                float: left;
            }

            .general_form  label {
                display: block;
                float: left;
                font-weight: bold;
                width: 105px;
                line-height: 22px;
            }

            .general_form .inputs {
                float: left;
/*                width: 520px;*/
            }

            .general_form .input_wrapper {
                background: url("layout/site/forms/input_text2.gif") repeat-x scroll 0 0 #FEFEFE;
                border: 1px solid #CECECE;
                display: block;
                float: left;
                line-height: normal;
                margin: 0 8px 0 0;
                padding: 2px 4px;
                width: 194px;
            }
            .input_wrapper select {
                width: 100%;
            }
            .general_form .blank {
                background: none repeat scroll 0 0 transparent;
                border: 0 none;
            }
            .general_form .medium_input {
                width: 86px;
            }
            .general_form .short_input {
                overflow: hidden;
                width: 48px;
            }
            .general_form .input_wrapper input.text {
                background: none repeat scroll 0 0 transparent;
                border: 0 none;
                display: block;
                margin: 0;
                padding: 0;
                width: 100%;
            }
            .send_form_btn {
                background-color: #339FD0;
                background-image: url("/images/layout/site/forms/send_form_middle.gif");
            }
            .send_form_btn span {
                background-image: url("/images/layout/site/forms/send_form_left.gif");
            }
            .send_form_btn span span {
                background-image: url("/images/layout/site/forms/send_form_right.gif");
            }

        </style>
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/jquery-ui.js"></script>
        <script type="text/javascript" src="/js/jquery.dform.js"></script>
        <?php echo $this->headScript() ?>
    </head>

    <body>
        <!--[if !IE]>start wrapper<![endif]-->
        <div id="wrapper">

            <?= $this->layout()->content ?>

        </div>
        <!--[if !IE]>end wrapper<![endif]-->
    </body>
</html>
