<style>

    #login
    {
        background-color: #fff;
        background-image: -webkit-gradient(linear, left top, left bottom, from(#fff), to(#eee));
        background-image: -webkit-linear-gradient(top, #fff, #eee);
        background-image: -moz-linear-gradient(top, #fff, #eee);
        background-image: -ms-linear-gradient(top, #fff, #eee);
        background-image: -o-linear-gradient(top, #fff, #eee);
        background-image: linear-gradient(top, #fff, #eee);
        height: 240px;
        width: 400px;
        margin: -150px 0 0 -230px;
        padding: 30px;
        position: absolute;
        top: 51%;
        left: 50%;
        z-index: 0;
        -moz-border-radius: 3px;
        -webkit-border-radius: 3px;
        border-radius: 3px;

    }

    #login:before
    {
        content: '';
        position: absolute;
        z-index: -1;
        border: 1px dashed #ccc;
        top: 5px;
        bottom: 5px;
        left: 5px;
        right: 5px;
        -moz-box-shadow: 0 0 0 1px #fff;
        -webkit-box-shadow: 0 0 0 1px #fff;
        box-shadow: 0 0 0 1px #fff;
    }

    /*--------------------*/

        h1
        {
            text-shadow: 0 1px 0 rgba(255, 255, 255, .7), 0px 2px 0 rgba(0, 0, 0, .5);
            text-transform: uppercase;
            text-align: center;
            color: #666;
            margin: 0 0 30px 0;
            letter-spacing: 4px;
            font: normal 26px/1 Verdana, Helvetica;
            position: relative;
        }
/*
    h1:after, h1:before
    {
        background-color: #777;
        content: "";
        height: 1px;
        position: absolute;
        top: 15px;
        width: 120px;
    }

    h1:after
    {
        background-image: -webkit-gradient(linear, left top, right top, from(#777), to(#fff));
        background-image: -webkit-linear-gradient(left, #777, #fff);
        background-image: -moz-linear-gradient(left, #777, #fff);
        background-image: -ms-linear-gradient(left, #777, #fff);
        background-image: -o-linear-gradient(left, #777, #fff);
        background-image: linear-gradient(left, #777, #fff);
        right: 0;
    }

    h1:before
    {
        background-image: -webkit-gradient(linear, right top, left top, from(#777), to(#fff));
        background-image: -webkit-linear-gradient(right, #777, #fff);
        background-image: -moz-linear-gradient(right, #777, #fff);
        background-image: -ms-linear-gradient(right, #777, #fff);
        background-image: -o-linear-gradient(right, #777, #fff);
        background-image: linear-gradient(right, #777, #fff);
        left: 0;
    }
*/
    /*--------------------*/

    fieldset
    {
        border: 0;
        padding: 0;
        margin: 0;
    }

    /*--------------------*/

    #inputs input
    {
        /*background: #f1f1f1 url(http://icons.iconarchive.com/icons/wwalczyszyn/android-style/48/Mail-icon.png) no-repeat;*/
        padding: 15px 15px 15px 30px;
        margin: 0 0 10px 0;
        width: 353px; /* 353 + 2 + 45 = 400 */
        border: 1px solid #ccc;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border-radius: 5px;
        -moz-box-shadow: 0 1px 1px #ccc inset, 0 1px 0 #fff;
        -webkit-box-shadow: 0 1px 1px #ccc inset, 0 1px 0 #fff;
        box-shadow: 0 1px 1px #ccc inset, 0 1px 0 #fff;
    }

    #username
    {
        background-position: 5px -2px !important;
    }

    #password
    {
        background-position: 5px -52px !important;
    }

    #inputs input:focus
    {
        background-color: #fff;
        border-color: #e8c291;
        outline: none;
        -moz-box-shadow: 0 0 0 1px #e8c291 inset;
        -webkit-box-shadow: 0 0 0 1px #e8c291 inset;
        box-shadow: 0 0 0 1px #e8c291 inset;
    }

    /*--------------------*/
    #actions
    {
        margin: 0px 0 0 0;
    }

    #submit
    {
        background-color: #ffffff;
        background-image: -webkit-gradient(linear, left top, left bottom, from(#708090), to(#778899));
        background-image: -webkit-linear-gradient(top, #708090, #778899);
        background-image: -moz-linear-gradient(top, #708090, #778899);
        background-image: -ms-linear-gradient(top, #708090, #778899);
        background-image: -o-linear-gradient(top, #708090, #778899);
        background-image: linear-gradient(top, #708090, #778899);

        -moz-border-radius: 3px;
        -webkit-border-radius: 3px;
        border-radius: 3px;

        text-shadow: 0 1px 0 rgba(255,255,255,0.5);

        -moz-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
        -webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;
        box-shadow: 0 0 1px rgba(0, 0, 0, 0.3), 0 1px 0 rgba(255, 255, 255, 0.3) inset;

        border-width: 1px;
        border-style: solid;
        border-color: #ffffff;

        float: left;
        height: 35px;
        padding: 0;
        width: 120px;
        cursor: pointer;
        font: bold 15px Arial, Helvetica;
        color: #ffffff;
    }

    #submit:hover,#submit:focus
    {
        background-color: #fddb6f;
        background-image: -webkit-gradient(linear, left top, left bottom, from(#ffb94b), to(#fddb6f));
        background-image: -webkit-linear-gradient(top, #ffb94b, #fddb6f);
        background-image: -moz-linear-gradient(top, #ffb94b, #fddb6f);
        background-image: -ms-linear-gradient(top, #ffb94b, #fddb6f);
        background-image: -o-linear-gradient(top, #ffb94b, #fddb6f);
        background-image: linear-gradient(top, #ffb94b, #fddb6f);
    }

    #submit:active
    {
        outline: none;

        -moz-box-shadow: 0 1px 4px rgba(0, 0, 0, 0.5) inset;
        -webkit-box-shadow: 0 1px 4px rgba(0, 0, 0, 0.5) inset;
        box-shadow: 0 1px 4px rgba(0, 0, 0, 0.5) inset;
    }

    #submit::-moz-focus-inner
    {
        border: none;
    }

    #actions a
    {
        color: #3151A2;
        float: right;
        line-height: 35px;
        margin-left: 10px;
    }

    /*--------------------*/

    #back
    {
        display: block;
        text-align: center;
        position: relative;
        top: 60px;
        color: #999;
    }



</style>

<?php if($this->msg != ""): ?>
    <div class="alert alert-<?php if($this->tipoAlerta != ""){ echo $this->tipoAlerta; } ?> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Atenção!</strong> <?php echo $this->msg; ?>
    </div>
<?php endif; ?>
<?php echo $this->email; ?>

<form id="login" method="POST" action="/acesso/login/recuperar">
    <h1>Recuperação de Senha</h1>
    <div style="float: left; position: relative; width: 398px; text-align: left;"><?php $this->mensagem(); ?></div>
        <fieldset id="inputs">
            <input id="username" name="email" type="email" placeholder="Informe seu e-mail" autofocus required>
        </fieldset>
    <fieldset id="actions">
        <input type="submit" id="submit" value="Enviar">
        <input type="button" id="submit" value="Voltar" onclick="location.href='/'">
    </fieldset>
</form>

<!--
<br />
<br />
<br />

<div style='padding: 10px 10px 10px 10px; height: 600px; width: 400px; background-color: lightgreen; box-shadow: darkgreen 10px 10px 8px; text-align: center'>
    <h2>Você solicitou a recuperação de
        <br />
        senha do sistema</h2>
    <br />
    <h1>e-SUS Chamado</h1>
    <br />
    <br />
    <h4>Para concluir a recuperação de sua senha, clique no link abaixo!</h4>
    <br />
    <div style='width: 550px; background-color: yellow'>
        <h5><a href='http://suporte-esus.datasus.gov.br/acesso/login/recuperar/solicitacao/<?php //if($this->senha != ''){ echo $this->senha; } ?>'>
                http://suporte-esus.datasus.gov.br/acesso/login/recuperar/form/<?php //if($this->senha != ''){ echo $this->senha; } ?></a></h5>
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <div>
        <h6>Suporte e-SUS: suporteesushospitalar@saude.gov.br</h6>
    </div>
</div>
-->















