<script>
$(document).ready(function() {
        $(".formValidate").validate(); 

       if($('#totalrecords').val() != 0){
               $('#paginacao').smartpaginator({ totalrecords: $('#totalrecords').val(), recordsperpage: 10, datacontainer: 'mt', dataelement: 'tr', initval: 0, theme: 'blue',controlsalways:false });
       }	

});
</script>
<script>
    $(document).ready(function() {

        $('#submit').attr('disabled', 'disabled');

        $('#salvar').mouseenter(function () {
            var no_ambiente = $('#no_ambiente').val();
            var co_ambiente = $('#co_ambiente').val();

            if(co_ambiente < 1){
                if(no_ambiente === "") {
                    $('#no_amb_vazio').show();
                    $('#erro').show();
                    $('#no_amb_usado').hide();
                }else{
                    $.post('/manutencao/ambiente/validar', {no_ambiente: no_ambiente}, function (data) {
                        if (data === 'false') {
                            $('#submit').attr('disabled', 'disabled');
                            $('#no_amb_usado').show();
                            $('#erro').show();
                        } else {
                            $('#submit').removeAttr('disabled');
                            $('#erro').hide();
                            $('#no_amb_usado').hide();
                            $('#no_amb_vazio').hide();
                        }
                    });
                }
            }else{
                if(no_ambiente === "") {
                    $('#no_amb_vazio').show();
                    $('#no_amb_usado').hide();
                    $('#erro').show();
                    $('#submit').attr('disabled', 'disabled');
                }else{
                    $('#no_amb_vazio').hide();
                    $('#erro').hide();
                    $.post('/manutencao/ambiente/validar', {no_ambiente: no_ambiente}, function (data) {
                        if (data === 'false') {
                            $('#submit').attr('disabled', 'disabled');
                            //$('#no_amb_usado').show();
                            $('#no_amb_vazio').hide();
                        } else {
                            $('#submit').removeAttr('disabled');
                            //$('#no_amb_usado').hide();
                        }
                    });
                }
            }
        });




    });
        /*
        $('#form-usuario').change(function(){
            var no_ambiente = $('#no_ambiente').val();
            
            if(no_ambiente !== ""){
                $.get('/manutencao/ambiente/validar/', {no_ambiente: no_ambiente}, function(data){
                    if(data !== 'true'){
                        $('#submit').attr('disabled', 'disabled');
                        $('#no_amb_usado').fadeIn('slow');
                        $('#no_ambiente').css("border", "1px solid #F00");
                    }else{
                        $('#submit').removeAttr('disabled');
                        $('#no_amb_usado').fadeOut('fast');
                        $('#no_ambiente').css("border", "1px solid #cccccc");
                    }
                });
            }
        });
    });*/
</script>
<style>
form label.error{ 
    text-align: right;
    width: 100%;
}
form label.error {
    color: red;
    font-style: italic;
    font-size: 0.9em;
    margin-top: -10px;
}



input {
    border: 1px solid black;
}
input.checkbox {
    border: medium none;
}
input:focus {
    border: 1px dotted black;
}
input.error {
    border: 1px dotted red;
}
</style>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="" class="tip-bottom" data-original-title="Principal"><i class="icon-home"></i>Principal</a>
        -> 
        <a href="/manutencao/ambiente/listar" class="tip-bottom" data-original-title="" title="">Ambiente</a>
         -> Cadastro de Ambiente
    </div>
    <h1>Cadastro de Ambiente</h1>
</div>

<div class="content-box cadProf" id="boxGrid"><!-- Start Content Box GRID -->				
    <div class="content-box-content">					
        <div id="cadProf" class="tab-content default-tab"> <!-- INICIO TAB 1-->																												
            <?php echo  $this->mensagem(); ?>
                <form action="/manutencao/ambiente/adicionar" method="post" class="formValidate" id="form-usuario">
                   	<input type="hidden" value="<?php print $this->aObjAmbiente->getCoAmbiente()?>" name="co_ambiente" id="co_ambiente">
                	<div class="dados">
                            
                        <div class="linha">
                            <div class="campos">
                                <div class="label">
                                        Nome do Ambiente 
                                </div> 
                                <div>
                                        <input id="no_ambiente" name="no_ambiente" type="text" class="span5" value="<?php echo $this->no_amb; ?>" />
                                </div>
                                <!-- Mensagem dizendo que o nome do projeto já está em uso. -->
                                <div id="no_amb_usado" style="width: 300px; display: none; color: red; position: absolute; top: 50px; left: 300px">
                                    <em>Este nome já está em uso.</em>
                                </div>
                                <!-- Mensagem dizendo que o campo está vazio. -->
                                <div id="no_amb_vazio" style="width: 300px; display: none; color: red; position: absolute; top: 50px; left: 300px">
                                    <em>Esse campo deve ser preenchido.</em>
                                </div>
                            </div>
                        </div>
                        <br />
                        <br />
                       	   <!-- <a href="/manutencao/ambiente/listar" class="tip-bottom" data-original-title="" title=""> <input class="button_blue" value="Voltar" type="button" /></a>
	                       <input class="button_blue" value="Salvar" type="submit" /> -->
                    </div>

                    <!-- Mensagem informando um erro no formulário. -->
                    <div id="erro" style="width: 500px; display: none; color: red">
                        <em>Um erro ocorreu no preenchimento de algum campo do formulário.</em>
                    </div>

                    <div class="row-fluid">
                        <div class="span12" id="salvar">
                            <div class="form-actions">
                                <button id="submit" class="btn btn-primary" type="submit">Salvar</button>
                                <a href="/manutencao/ambiente/listar/num_linhas/<?php echo $this->num_linhas; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porAmbiente/<?php echo $this->porAmbiente; ?>/coluna/<?php echo $this->coluna; ?>/ordem/<?php echo $this->ordem; ?>/pg/<?php echo $this->pg; ?>" class="btn" data-original-title="" title="">Voltar</a>
                            </div>	
                        </div>
                    </div>
                        
                </form>
               <div class="clear"></div><!-- End .clear -->																														
        </div> 
        <!-- End #tab1 --> 	
        <div id="listaProf" class="tab-content">
            <!-- Inicio tab 2 -->
            <!-- TAB LISTA DE PROFISSIONAL -->																													
        </div> 
        <!-- End #tab2 -->			
    </div> <!-- End .content-box-content -->				
</div> <!-- End BOX GERAL GRID--> 
<!-- END BOX CRUD --> 
