<script src="/js/rel.chamado.js"></script>
<script type="text/javascript" src="/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //$('table').tablesorter();

        $('#mensagem').show();
        $('#submit_pesquisa').prop('disabled', true);
        $('#tipoBusca').change(function(){
            var valor = $("#tipoBusca").val();

            if(valor == 0) {
                $('#mensagem').show();
                $('#porNome').hide();
                $('#porAmbiente').hide();
                $('#porOrgao').hide();
            } else if(valor == 1) {
                $('#mensagem').hide();
                $('#porNome').show();
                $('#porAmbiente').hide();
                $('#porOrgao').hide();
                $('#porNome').keyup(function(){
                    if($('#porNome').val()=='') {
                        $('#submit_pesquisa').prop('disabled', true);
                    }else{
                        $('#submit_pesquisa').prop('disabled', false);
                    }
                });
            } else if(valor == 2) {
                $('#mensagem').hide();
                $('#porNome').hide();
                $('#porAmbiente').show();
                $('#porOrgao').hide();
                $('#porAmbiente').change(function(){
                    if($('#porAmbiente').val()=='') {
                        $('#submit_pesquisa').prop('disabled', true);
                    }else{
                        $('#submit_pesquisa').prop('disabled', false);
                    }
                });
            } else if(valor == 3) {
                $('#mensagem').hide();
                $('#porNome').hide();
                $('#porAmbiente').hide();
                $('#porOrgao').show();
                $('#porOrgao').change(function(){
                    if($('#porOrgao').val()=='') {
                        $('#submit_pesquisa').prop('disabled', true);
                    }else{
                        $('#submit_pesquisa').prop('disabled', false);
                    }
                });
            }
        });

        $('#num_pagina_select').change(function(){
            $('#form_num_pagina_select').submit();
        });
    });
</script>


<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="" class="tip-bottom" data-original-title="Principal"><i class="icon-home"></i> Principal</a>
        -> 
        <a href="/manutencao/projeto/listar" class="tip-bottom" data-original-title="" title="">Projeto</a>
         -> Lista de Projetos
    </div>
</div>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">

            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <!-- Tudo que você queira escondido em 940px ou menos, coloque aqui -->
            <div class="nav-collapse collapse">

                <ul class="nav pull-right">
                    <!-- <li><a href="#">Nr Chamado</a></li> -->
                    <li class="divider-vertical"></li>
                    <li>
                        <form class="navbar-form " id="form_load" action="" method="post">
                            <div class="input-append" style="margin-bottom: 0px;">
                                <input type="hidden" name="num_linhas_select" id="o_num_linhas_select" value="<?php echo $this->numLinhasSelect; ?>" />

                                <select name="oTipoBusca" id="tipoBusca" style="width: 165px; top: -5px">
                                    <option value="" selected="selected">Buscar por...</option>
                                    <option value="1">Nome</option>
                                    <option value="2">Ambiente</option>
                                    <option value="3">Órgão</option>
                                </select>

                                <input type="text" class="span8" name="mensagem" id="mensagem"
                                       style="width: 150px; display: none" readonly
                                       title="Selecione um tipo de busca"
                                       alt="Selecione um tipo de busca"
                                       placeholder="Selecione um tipo de busca"/>

                                <input type="text" class="span8" name="oPorNome" id="porNome"
                                       style="width: 150px; display: none"/>

                                <select class="span8" name="oPorAmbiente" id="porAmbiente" style="width: 164px; top: -5px; display: none">
                                    <option value="">Selecione...</option>
                                    <?php foreach($this->ambientes as $ambiente): ?>
                                        <option value="<?php echo $ambiente->getCoAmbiente(); ?>"><?php echo $ambiente->getNoAmbiente(); ?></option>
                                    <?php endforeach; ?>
                                </select>

                                <select class="span8" name="oPorOrgao" id="porOrgao" style="width: 164px; top: -5px; display: none">
                                    <option value="">Selecione...</option>
                                    <?php foreach($this->orgaos as $orgao): ?>
                                        <option value="<?php echo $orgao->getCoOrgao(); ?>"><?php echo $orgao->getNoOrgao(); ?></option>
                                    <?php endforeach; ?>
                                </select>

                                <button id="submit_pesquisa" type="submit" class="btn"><i class="icon-search"></i></button>
                                <a class="btn btn-default" href="/manutencao/projeto/listar"> <i class="icon-undo"></i></a>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="loading" style="display: none">
    <img src="/images/waiting.gif" width="100" height="100">
    <br />
</div>

<div>
    <form action="" method="post" id="form_num_pagina_select">
        <h5 style="float: left; padding-right: 15px"><b>Quantidade de resultados por página:</b></h5>
        <input type="hidden" name="filtro" id="filtro" value="<?php echo $this->filtro; ?>" />

        <input type="hidden" name="pg" id="o_pg" value="<?php echo $this->pg; ?>" />
        <input type="hidden" name="ordem" id="o_ordem" value="<?php echo $this->ordem; ?>" />
        <input type="hidden" name="coluna" id="o_coluna" value="<?php echo $this->coluna; ?>" />
        <input type="hidden" name="oTipoBusca" id="tipoBusca" value="<?php echo $this->tipoBusca; ?>" />
        <input type="hidden" name="oPorNome" id="porNome" value="<?php echo $this->porNome; ?>" />
        <input type="hidden" name="oPorAmbiente" id="porAmbiente" value="<?php echo $this->porTipo; ?>" />
        <input type="hidden" name="oPorOrgao" id="porOrgao" value="<?php echo $this->porProjeto; ?>" />
        <input type="hidden" name="num_linhas_select" id="o_num_linhas_select" value="<?php echo $this->numLinhasSelect; ?>" />

        <!--<input type="hidden" name="num_linhas_url" id="num_linhas_url" value="<?php //echo $this->numLinhasSelect; ?>" />-->
        <select style="width: 70px" id="num_pagina_select" name="num_linhas_select">
            <option value="15" <?php if($this->numLinhasSelect == 15){ echo " selected"; } ?>>15</option>
            <option value="50" <?php if($this->numLinhasSelect == 50){ echo " selected"; } ?>>50</option>
            <option value="100" <?php if($this->numLinhasSelect == 100){ echo " selected"; } ?>>100</option>
        </select>
    </form>
</div>

<script type="text/javascript">
    function trocaOrdem(asc_desc){
        if(asc_desc === "asc"){
            asc_desc = "desc";
        }else if(asc_desc === "desc"){
            asc_desc = "asc";
        }

        return asc_desc;
    }

    $(document).ready(function() {
        $("#1").click(function () {
            var asc_desc = $("#nr_chamado_asc_desc").val();
            var ordem = trocaOrdem(asc_desc);

            $(location).attr('href', '/manutencao/projeto/listar/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porAmbiente/<?php echo $this->porAmbiente; ?>/porOrgao/<?php echo $this->porOrgao; ?>/pg/<?php echo $this->pg; ?>/coluna/1/ordem/' + ordem);
        })
    });
</script>

<input type="hidden" id="nr_chamado_asc_desc" name="nr_chamado_asc_desc" value="<?php echo $this->ordem; ?>">

<div class="">
    <div class="row-fluid">
        <?php $this->mensagem(); ?>
        <div class="">
        <div class="widget-box">
          <div class="widget-title">
             <h5> <i class="icon-list-alt"></i> Lista de Projetos</h5> 
          </div>
            <div class="widget-content nopadding">
            <input type="hidden" name="totalrecords" id="totalrecords" value="<?php print count($this->aObjProjeto);?>" />

                <?php if(CO_PERFIL == 1) { ?>

                    <table class="table table-bordered table-striped" id="mt">
                        <thead>
                        <tr>
                            <th id="1" style="cursor: pointer" class="span3">Nome
                                <?php
                                if ($this->coluna == 1) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                            <th class="span3">Ambiente</th>
                            <th class="span3">Órgão</th>
                            <th class="span2">Ação</th>
                        </tr>

                        </thead>
                        <tbody>
                        <?php $i = 0;

                        foreach ($this->aObjProjeto as $objProjeto) { ?>
                            <tr <?php if (($i % 2) == 0) { ?>
                                class="alt-row"
                            <?php } ?>
                                >
                                <td><?php print $objProjeto->getNoProjeto(); ?></td>
                                <td>
                                    <?php foreach ($objProjeto->getRlProjetoVersaoAmbs() as $rlProjVersaoAmb){ ?>
                                        <?php print $rlProjVersaoAmb->getAmbiente()->getNoAmbiente()."; ";?>
                                    <?php }?>
                                </td>
                                <td>
                                    <?php

                                    foreach ($objProjeto->getRlOrgaoProjetos() as $rlOrgaoPrejeto){
                                        print $rlOrgaoPrejeto->getOrgao()->getNoOrgao()."; ";
                                    } ?>
                                </td>
                                <td>
                                    <!-- Icons -->
                                    <div class="btn-group">
                                        <a title="Editar" href="/manutencao/projeto/adicionar/co_projeto/<?php print $objProjeto->getCoProjeto(); ?>/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porAmbiente/<?php echo $this->porAmbiente; ?>/porOrgao/<?php echo $this->porOrgao; ?>/coluna/<?php echo $this->coluna; ?>/ordem/<?php echo $this->ordem; ?>/pg/<?php echo $this->pg; ?>" class="btn btn-small"><i class="icon-edit"></i></a>
                                        <a title="Excluir" href="javascript:if (confirm('Deseja realmente excluir este Projeto?')) window.location = '/manutencao/projeto/excluir/co_projeto/<?php print $objProjeto->getCoProjeto(); ?>'; " class="btn btn-small"><i class="icon-remove"></i></a>
                                    </div>
                                </td>


                            </tr>
                            <?php $i++;
                        } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="18" style="font-weight: bold">
                                <div class="pull-right">Total de Registros: <?php echo $this->oTotal == '' ? count($this->oTarefa) : $this->oTotal;?></div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>

                <?php } else { ?>

                    <table class="table table-bordered table-striped" id="mt">
                        <thead>
                        <tr>
                            <th id="1" style="cursor: pointer" class="span3">Nome
                                <?php
                                if ($this->coluna == 1) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                            <th id="2" style="cursor: pointer" class="span3">Ambiente
                                <?php
                                if ($this->coluna == 2) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                            <th id="3" style="cursor: pointer" class="span3">Órgão
                                <?php
                                if ($this->coluna == 3) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                        </tr>

                        </thead>
                        <tbody>
                        <?php $i = 0;

                        foreach ($this->aObjProjeto as $objProjeto) { ?>
                            <tr <?php if (($i % 2) == 0) { ?>
                                class="alt-row"
                            <?php } ?>
                                >
                                <td><?php print $objProjeto->getNoProjeto(); ?></td>
                                <td>
                                    <?php foreach ($objProjeto->getRlProjetoVersaoAmbs() as $rlProjVersaoAmb){ ?>
                                        <?php print $rlProjVersaoAmb->getAmbiente()->getNoAmbiente()."; ";?>
                                    <?php }?>
                                </td>
                                <td>
                                    <?php

                                    foreach ($objProjeto->getRlOrgaoProjetos() as $rlOrgaoPrejeto){
                                        print $rlOrgaoPrejeto->getOrgao()->getNoOrgao()."; ";
                                    } ?>
                                </td>
                            </tr>
                            <?php $i++;
                        } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="18" style="font-weight: bold">
                                <div class="pull-right">Total de Registros: <?php echo $this->oTotal == '' ? count($this->oTarefa) : $this->oTotal;?></div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>

                <?php } ?>

                <div class="pagination pagination-centered">
                    <ul>
                        <?php echo $this->pagination; ?>
                    </ul>
                </div>
        </div> <!-- End #tab2 -->
   		 <br />
        <?php if(CO_PERFIL == 1) { ?>
             <div class="row-fluid">
                <div class="span12">
                    <div class="form-actions">
                        <a class="btn btn-primary" href="/manutencao/projeto/adicionar/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porAmbiente/<?php echo $this->porAmbiente; ?>/porOrgao/<?php echo $this->porOrgao; ?>/coluna/<?php echo $this->coluna; ?>/ordem/<?php echo $this->ordem; ?>/pg/<?php echo $this->pg; ?>">Cadastrar</a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
  
</div> <!-- End BOX GERAL GRID--> 
<!-- END BOX CRUD --> 
</div>
</div>

