<style xmlns="http://www.w3.org/1999/html">
    .table td{
        line-height: 11px  !important;
        font-size:12px  !important;
        padding: 5px  !important;
    }
    body {
        padding:42px 0 40px 0;
    }

</style>


<script src="/js/Chart.min.js"></script>
<script src="/js/relatorio.js"></script>
<script src="/js/rel.chamado.js"></script>


<!--Load the AJAX API-->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

    // Load the Visualization API and the piechart package.
    google.load('visualization', '1.0', {'packages':['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

        // Create the data table.
        var data = new google.visualization.arrayToDataTable([
            ['Orgaos', 'Hours per Day'],

            <?php foreach($this->orgaos as $orgao) : ?>
                [<?php print_r("'".$orgao['no_orgao']."'"); ?>,     <?php print_r($orgao['quantidade']); ?>],
            <?php endforeach; ?>
        ]);

        // Set chart options
        var options = {
            title: 'Hospitais que lideram na quantidade de chamados abertos.',
            is3D: true,
        };

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
    }
</script>

<div class="row-fluid">
    <div class="span12">
        <div style="padding-bottom: 10px">
            <button onclick="javascript:window.print()" class="btn btn-primary">
                Imprimir
                <i class="icon-print"></i>
            </button>
        </div>

        <h5>
            <i class="icon-list"></i> Relatório quantitativo de chamados por órgão.
        </h5>

        <div style="float: left">
            <!--Div that will hold the pie chart-->
            <div id="piechart_3d" style="width: 600px; height: 400px"></div>
        </div>

        <div style="float: right">
            <table class="table table-bordered">
                <thead>
                <tr style="background-color: silver">
                    <td width="80"><b>Mnemônico</b></td>
                    <td width="300"><b>Nome do órgão</b></td>
                    <td width="80"><b>Quantitativo de chamados</b></td>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->orgaos as $orgao) : ?>
                    <tr>
                        <td><?php print_r($orgao['sg_orgao']); ?></td>
                        <td><?php print_r($orgao['no_orgao']); ?></td>
                        <td><?php print_r($orgao['quantidade']); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr style="background-color: silver">
                        <td><b>Total</b></td>
                        <td></td>
                        <td><b><?php echo $this->total; ?></b></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>


</div>


<div>
    <iframe src="https://mapsengine.google.com/map/embed?mid=z21BpM7oMNG0.kzenW_igmXzY" width="540" height="180"></iframe>
</div>

