<style>
    .table td{
        line-height: 11px  !important;
        font-size:12px  !important;
        padding: 5px  !important;
    }
    body {
        padding:42px 0 40px 0;
    }

</style>


<script src="/js/Chart.min.js"></script>
<script src="/js/relatorio.js"></script>

<script type="text/javascript">
    var randomnb = function(){ return Math.round(Math.random()*200)};
</script>


<script src="/js/rel.chamado.js"></script>
<script type="text/javascript">
    $(document).ready(function() {

        $('#add1').click(function (){
            $('#arquivo2').show();
        });

        $('#add2').click(function (){
            $('#arquivo3').show();
        });

        $('#reset1').click(function(){
            $('#file1').val('');
        });

        $('#reset2').click(function(){
            $('#file2').val('');
        });

        $('#reset3').click(function(){
            $('#file3').val('');
        });

        $('#reset').click(function(){
            $('#arquivo').val('');
        });

    });
</script>



<div class="row-fluid">
    <div class="span12">
        <div style="padding-bottom: 10px">
            <button onclick="javascript:window.print()" class="btn btn-primary">
                Imprimir
                <i class="icon-print"></i>
            </button>
        </div>
        <?php $this->mensagem(); ?>
        <h5>
            <i class="icon-list"></i> Relatório de chamados por projeto no mês.
        </h5>

        <div class="navbar" style="">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <form action="/relatorio/index/chamado-mes" method="post" id="form">
                    <div class="nav-collapse collapse">
                        <ul class="nav">

                            <li class="filtro_relatorio">
                                <label for="cod_projeto">Projeto:</label>
                                <select id="cod_projeto" name="cod_projeto" style="width: 200px" >
                                    <?php if(count($this->projetos) > 0){ ?>
                                        <?php foreach($this->projetos as $projeto){ ?>
                                            <option value="<?php echo $projeto->getCoProjeto(); ?>"
                                                <?php if($projeto->getCoProjeto() == $this->cod_projeto){
                                                    echo " selected ";
                                                } ?>>
                                                <?php echo $projeto->getNoProjeto(); ?>
                                            </option>
                                        <?php }
                                    } ?>
                                </select>
                            </li>

                            <li class="filtro_relatorio">
                                <label for="cod_ambiente">Ambiente:</label>
                                <select id="cod_ambiente" name="cod_ambiente" style="width: 150px">
                                    <?php if(count($this->ambientes) > 0){ ?>
                                        <option value="">Todos</option>
                                        <?php foreach($this->ambientes as $ambiente){ ?>
                                            <option value="<?php echo $ambiente->getCoAmbiente(); ?>"
                                                <?php if($ambiente->getCoAmbiente() == $this->cod_ambiente){
                                                    echo " selected ";
                                                } ?>>
                                                <?php echo $ambiente->getNoAmbiente(); ?>
                                            </option>
                                        <?php }
                                    } ?>
                                </select>
                            </li>-

                            <li class="filtro_relatorio">
                                <label for="cod_orgao">Órgão:</label>
                                <select id="cod_orgao" name="cod_orgao" style="width: 350px">
                                    <?php if(count($this->orgaos) > 0){ ?>
                                        <option value="">Todos</option>
                                        <?php foreach($this->orgaos as $orgao){ ?>
                                            <option value="<?php echo $orgao->getCoOrgao(); ?>"
                                                <?php if($orgao->getCoOrgao() == $this->cod_orgao) {
                                                    echo " selected ";
                                                } ?>>
                                                <?php echo $orgao->getNoOrgao(); ?>
                                            </option>
                                        <?php }
                                    } ?>
                                </select>
                            </li>

                            <li class="filtro_relatorio">
                                <label for="ano">Ano:</label>
                                <select id="ano" name="ano" style="width: 70px">
                                    <?php foreach($this->oAno as $ano) { ?>
                                        <option value = "<?php echo $ano['ano'] ?>"
                                            <?php if($ano['ano'] == $this->anoPost){ echo " selected "; } ?>>
                                            <?php echo $ano['ano'] ?></option >
                                    <?php } ?>
                                </select>
                            </li>

                            <li class="filtro_relatorio">
                                <label for="mes">Mês:</label>
                                <select id="mes" name="mes" style="width: 100px">
                                    <?php foreach($this->noMeses as $key => $value){ ?>
                                        <option value="<?php echo $key; ?>"
                                            <?php if($this->mesPost == $key){ echo " selected "; }?>>
                                            <?php echo $value; ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </li>

                            <li class="filtro_relatorio">
                                <label for="status">Status:</label>
                                <select id="status" name="status" style="width: 100px">
                                    <option value="">Todos</option>
                                    <?php foreach($this->status as $status){ ?>
                                        <option value="<?php echo $status->getCoStatus(); ?>"
                                            <?php if($status->getCoStatus() == $this->oStatus){ echo " selected "; }?>>
                                            <?php echo $status->getNoStatus(); ?>
                                        </option>
                                    <?php } ?>
                                </select>
                            </li>

                            <li class="filtro_relatorio botao_gerar">
                                <input type="submit" value="Gerar" class="btn btn-primary">
                            </li>

                        </ul>
                    </div>
                    </form>
                </div>
            </div>
        </div>

        <div>
            <table class="table">
                <thead>
                <tr>
                    <td><b>Projeto</b></td>
                    <td><b>Ambiente</b></td>
                    <td><b>Órgão</b></td>
                    <td><b>Ano</b></td>
                    <td>
                        <b>Total de chamados no mês de
                            <?php
                                echo $this->oMes;
                            ?>
                        </b>
                    </td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <?php
                        foreach ($this->projetos as $projeto) {
                            if ($projeto->getCoProjeto() == $this->cod_projeto){
                                echo $projeto->getNoProjeto();
                            }
                        }
                        ?>
                    </td>
                    <td>
                        <?php
                        if($this->cod_ambiente > 0) { //echo "<pre>"; print_r($this->orgaos);
                            foreach ($this->ambientes as $ambiente) {
                                if ($ambiente->getCoAmbiente() == $this->cod_ambiente){
                                    echo $ambiente->getNoAmbiente();
                                }
                            }
                        }else{
                            echo "Todos os ambientes";
                        }
                        ?>
                    </td>
                    <td>
                        <?php
                        if($this->cod_orgao > 0) { //echo "<pre>"; print_r($this->orgaos);
                            foreach ($this->orgaos as $orgao) {
                                if ($orgao->getCoOrgao() == $this->cod_orgao){
                                    echo $orgao->getNoOrgao();
                                }
                            }
                        }else{
                            echo "Todos os órgãos";
                        }
                        ?>
                    </td>
                    <td><?php echo $this->anoPost; ?></td>
                    <td><?php echo $this->totais; ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="box">
            <div class="box-chart" style="color: ">

                <canvas id="GraficoLine" style="width:100%; height: 450px;"></canvas>

                <script type="text/javascript">

                    var options = {
                        responsive:true
                    };

                    var data = {
                        labels: [
                            <?php print_r($this->diasNoMes); ?>
                        ],
                        datasets: [
                            {
                                <?php switch($this->cod_status){
                                     case 1:
                                        echo 'label: "Aberto",
                                        fillColor: "rgba(220,220,220,0.5)",
                                        strokeColor: "rgba(0,0,10,0.9)",
                                        highlightFill: "rgba(220,220,220,0.75)",
                                        highlightStroke: "rgba(220,220,220,1)",
                                        data: ['.$this->strJqueryGraficoMes.']';
                                    break;
                                    case 7:
                                        echo '
                                        label: "Atribuido",
                                        fillColor: "rgba(233,209,93,1)",
                                        strokeColor: "rgba(0,0,10,0.9)",
                                        highlightFill: "rgba(233,209,93,0.75)",
                                        highlightStroke: "rgba(220,220,220,1)",
                                        data: ['. $this->strJqueryGraficoMes .']';
                                    break;
                                    case 2:
                                        echo '
                                        label: "Em andamento",
                                        fillColor: "rgba(151,187,205,1)",
                                        strokeColor: "rgba(0,0,10,0.9)",
                                        highlightFill: "rgba(151,187,205,0.75)",
                                        highlightStroke: "rgba(220,220,220,1)",
                                        data: ['. $this->strJqueryGraficoMes .']';
                                    break;
                                    case 8:
                                        echo '
                                        label: "Resolvido",
                                        fillColor: "rgba(200,242,200,1)",
                                        strokeColor: "rgba(0,0,10,0.9)",
                                        highlightFill: "rgba(200,242,200,0.75)",
                                        highlightStroke: "rgba(220,220,220,1)",
                                        data: ['. $this->strJqueryGraficoMes .']';
                                    break;
                                    case 5:
                                        echo '
                                        label: "Fechado",
                                        fillColor: "rgba(0,0,0,0.5)",
                                        strokeColor: "rgba(0,0,10,0.9)",
                                        highlightFill: "rgba(0,0,0,0.5)",
                                        highlightStroke: "rgba(220,220,220,1)",
                                        data: ['. $this->strJqueryGraficoMes .']';
                                    break;
                                    default:
                                        echo '
                                        label: "Chamados abertos",
                                        fillColor: "rgba(220,220,220,0.5)",
                                        strokeColor: "rgba(0,0,10,0.9)",
                                        highlightFill: "rgba(220,220,220,0.75)",
                                        highlightStroke: "rgba(220,220,220,1)",
                                        data: ['. $this->strJqueryGraficoMes .']';
                                    }
                                ?>
                            }
                        ]
                    };

                    window.onload = function(){
                        var ctx = document.getElementById("GraficoLine").getContext("2d");
                        var LineChart = new Chart(ctx).Bar(data, options);
                    }
                </script>
            </div>
        </div>

        <br />

        <div style="margin-top: -15px;">
            <ul class="inline">
                <li><strong>Legenda:</strong></li>
                <li class="muted">Aberto</li>
                <li class="text-warning">Atríbuido</li>
                <li class="text-info"> Em Andamento </li>
                <li class="text-success">Resolvido</li>
                <li style="color: #484848">Fechado</li>
            </ul>
        </div>
    </div>
</div>