<div style="height: 500px; text-align: center;">
	<?php echo $this->mensagem(); ?>
	<h2>Suporte e-SUS</h2>
	    <div style="font-size:22px;text-align: justify;padding: 54px">

            <script type="text/javascript">
                $(document).ready(function(){
                    $('#alerta').show();

                    $('#fechar').click(function(){
                        $('#alerta').hide();
                    });
                });
            </script>

           <!-- <div id="alerta" style="
                width: 800px;
                height: 550px;
                background-color: rgba(227, 243, 255, 0.94);
                position: absolute;
                left: 18%;
                top: 20%;
                border-radius: 25px;
                padding: 20px 20px 20px 20px;
                font-size: 35px;
                text-justify: auto;
                box-shadow: 10px 10px 20px 0px;
                display: none">
                <div>
                    <p >No dia 27/02/2015, o sistema de chamados</p><br />
                    <p>técnicos ficará fora do ar a partir dàs 17:00h</p><br />
                    <p>para executarmos a migração dos dados para a</p><br />
                    <p>base de produção e o endereço </p><br />
                    <p>'<em style="color: midnightblue">dev-suporte-esus.datasus.gov.br</em>' deixará</p><br />
                    <p>de ser usado.</p>
                    <br />
                    <br />
                    <br />
                    <br />
                    <p>A partir do dia 02/03/2015, o endereço usado</p><br />
                    <p>pelos usuários deverá ser</p><br />
                    <p>'<a href="http://suporte-esus.datasus.gov.br" style="text-decoration: none">
                            <em style="color: midnightblue">suporte-esus.datasus.gov.br</em>
                        </a>'.</p>
                    <br />
                    <br />
                    <button style="" id="fechar" class="btn btn-primary">Fechar</button>
                </div>

            </div> -->

            <p>
                <!-- O Suporte e-SUS tem por finalidade disponibilizar e cadastrar todos os chamados feitos para a equipe do suporte e-SUS. -->
               Bem-vindos à página inicial do CHAMADO do e-SUS Hospitalar, e-SUS Report e Fila Cirúrgica.
            </p>
            <br />
            <br />
            <p>
               É o ponto de partida para obter ajuda para todos os módulos do sistema, enviando as inconsistências encontradas, tirando dúvidas, enviando sugestões e possíveis melhorias.
            </p>
	    </div>
</div>
