<div class="content-box cadProf" id="boxGrid"><!-- Start Content Box GRID -->				
    <div class="content-box-header">
        <h4 class="titleList">Listagem de Perfis</h4>
        <ul class="content-box-tabs" style="display: block;">
            <li><a href="/usuario/perfil/adicionar">Cadastrar</a></li>
            <li><a class="default-tab current" href="<?php print $this->baseUrl ?>/index">Listar</a></li>
        </ul>																												
        <div class="clear"></div>																												
    </div> <!-- End .content-box-header -->				
    <div class="content-box-content">					
        <div id="cadProf"> 
            <!-- TAB CADASTRO DE PERFIL -->																			
        </div> 
        <!-- End #tab1 --> 	
        <div id="listaProf" class="tab-content default-tab"><!-- Inicio tab 2 -->
            <?php 
                if (isset($this->atencao))
                    echo $this->atencao; 
                
                if (isset($this->sucesso))
                    echo $this->sucesso; 
                
                if (isset($this->error))
                    echo $this->error; 
                
                ?>            
            <table>																														
                <thead>
                    <tr>
                       <!-- <th>input type="checkbox" class="check-all"></th> -->
                        <th>Nome</th>																				   
                        <th>Descrição</th>                        
                        <th></th>
                    </tr>
                </thead>																													 
                <tbody>
                <?php $i = 0;
                    foreach ($this->aObjPerfil as $objPerfil) { ?>
                        <tr <? if (($i % 2) == 0) { ?>class="alt-row"<?php } ?>>
                            <td><?php print $objPerfil->getNoPerfil(); ?></td>
                            <td><?php print $objPerfil->getDsPerfilCrop(30); ?></td>
                            <td>
                                <!-- Icons -->
                                <a title="Editar" href="/usuario/perfil/adicionar/co_perfil/<?php print $objPerfil->getCoPerfil(); ?>"><img alt="Editar" src="/images/pencil.png"></a>
                                <a title="Excluir" href="javascript:remover('/usuario/perfil/excluir/co_perfil/<?php print $objPerfil->getCoPerfil(); ?>','este perfil?'); "><img alt="Excluir" src="/images/cross.png"></a>
                                <a title="Permissões para este Perfil" href="/usuario/permissao/lista/co_perfil/<?php print $objPerfil->getCoPerfil(); ?>"><img alt="Permissões para este perfil" src="/images/icon_permission.png"></a>
                            </td>
                        </tr>	                        
    <?php $i++;
 ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6">																					
                                <?php if ($this->paginas > 1) { ?>
                                <div class="pagination">
                                    <!--  <a href="#" title="First Page">&laquo; First</a><a href="#" title="Previous Page">&laquo; Previous</a> -->
                                    <?php
                                    for ($i = 1; $i < ($this->paginas + 1); $i++) {
                                        if ($this->pagina == $i) {
                                            $current = "current";
                                        } else {
                                            $current = "";
                                        }
                                        ?>
                                        <a href="/profissionais/index/index/pagina/<?= $i; ?>" class="number <?= $current; ?>" title="2" ><?= $i; ?></a>
                                <?php } ?>
                                    <!-- <a href="#" title="Next Page">Next &raquo;</a><a href="#" title="Last Page">Last &raquo;</a> -->
                                </div> <!-- End .pagination -->
<?php } ?>
                            <div class="clear"></div>

                        </td>
                    </tr>
                </tfoot>																														
            </table>																													
        </div> <!-- End #tab2 -->			
    </div> <!-- End .content-box-content -->				
</div> <!-- End BOX GERAL GRID--> 
<!-- END BOX CRUD --> 