<script src="/js/rel.chamado.js"></script>
<script type="text/javascript" src="/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        //$("table").tablesorter();

        $('#mensagem').show();
        $('#submit_pesquisa').prop('disabled', true);
        $('#tipoBusca').change(function(){
            var valor = $("#tipoBusca").val();

            if(valor == 0) {
                $('#mensagem').show();
                $('#porNome').hide();
                $('#porProjeto').hide();
            } else if(valor == 1) {
                $('#mensagem').hide();
                $('#porNome').show();
                $('#porProjeto').hide();
                $('#porNome').keyup(function(){
                    if($('#porNome').val()=='') {
                        $('#submit_pesquisa').prop('disabled', true);
                    }else{
                        $('#submit_pesquisa').prop('disabled', false);
                    }
                });
            } else if(valor == 2) {
                $('#mensagem').hide();
                $('#porNome').hide();
                $('#porProjeto').show();
                $('#porProjeto').change(function(){
                    if($('#porProjeto').val()=='') {
                        $('#submit_pesquisa').prop('disabled', true);
                    }else{
                        $('#submit_pesquisa').prop('disabled', false);
                    }
                });
            }
        });

        $('#num_pagina_select').change(function(){
            $('#form_num_pagina_select').submit();
        });
    });
</script>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="" class="tip-bottom" data-original-title="Principal"><i class="icon-home"></i> Principal</a>
        -> 
        <a href="/manutencao/modulo/listar" class="tip-bottom" data-original-title="" title="">Modulo</a>
         -> Lista de Módulos
    </div>
</div>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">

            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <!-- Tudo que você queira escondido em 940px ou menos, coloque aqui -->
            <div class="nav-collapse collapse">

                <ul class="nav pull-right">
                    <!-- <li><a href="#">Nr Chamado</a></li> -->
                    <li class="divider-vertical"></li>
                    <li>
                        <form class="navbar-form " id="form_load" action="" method="post">
                            <div class="input-append" style="margin-bottom: 0px;">
                                <input type="hidden" name="num_linhas_select" id="o_num_linhas_select" value="<?php echo $this->numLinhasSelect; ?>" />

                                <input type="hidden" name="pg" id="o_pg" value="<?php echo $this->pg; ?>" />
                                <input type="hidden" name="ordem" id="o_ordem" value="<?php echo $this->ordem; ?>" />
                                <input type="hidden" name="coluna" id="o_coluna" value="<?php echo $this->coluna; ?>" />

                                <select name="oTipoBusca" id="tipoBusca" style="width: 165px; top: -5px">
                                    <option value="" selected="selected">Buscar por...</option>
                                    <option value="1">Nome</option>
                                    <option value="2">Projeto</option>
                                </select>

                                <input type="text" class="span8" name="mensagem" id="mensagem"
                                       style="width: 150px; display: none" readonly
                                       title="Selecione um tipo de busca"
                                       alt="Selecione um tipo de busca"
                                       placeholder="Selecione um tipo de busca"/>

                                <input type="text" class="span8" name="oPorNome" id="porNome"
                                       style="width: 150px; display: none"/>

                                <select class="span8" name="oPorProjeto" id="porProjeto" style="width: 164px; top: -5px; display: none">
                                    <option value="">Selecione...</option>
                                    <?php foreach($this->aObjProjeto as $projeto): ?>
                                        <option value="<?php echo $projeto->getCoProjeto(); ?>"><?php echo $projeto->getNoProjeto(); ?></option>
                                    <?php endforeach; ?>
                                </select>

                                <button id="submit_pesquisa" type="submit" class="btn"><i class="icon-search"></i></button>
                                <a class="btn btn-default" href="/manutencao/modulo/listar"> <i class="icon-undo"></i></a>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php
//echo "<pre>";
//foreach($this->aObjProjeto as $a) {
//    if($a->getNoProjeto() != "") {
//        print_r($a);
//        echo "<br />";
//    }
//}
?>
<div id="loading" style="display: none">
    <img src="/images/waiting.gif" width="100" height="100">
    <br />
</div>

<div>
    <form action="" method="post" id="form_num_pagina_select">
        <h5 style="float: left; padding-right: 15px"><b>Quantidade de resultados por página:</b></h5>
        <input type="hidden" name="filtro" id="filtro" value="<?php echo $this->filtro; ?>" />

        <input type="hidden" name="pg" id="o_pg" value="<?php echo $this->pg; ?>" />
        <input type="hidden" name="ordem" id="o_ordem" value="<?php echo $this->ordem; ?>" />
        <input type="hidden" name="coluna" id="o_coluna" value="<?php echo $this->coluna; ?>" />
        <input type="hidden" name="oTipoBusca" id="tipoBusca" value="<?php echo $this->tipoBusca; ?>" />
        <input type="hidden" name="oPorNome" id="porNome" value="<?php echo $this->porNome; ?>" />
        <input type="hidden" name="oPorProjeto" id="porProjeto" value="<?php echo $this->porProjeto; ?>" />
        <input type="hidden" name="num_linhas_select" id="o_num_linhas_select" value="<?php echo $this->numLinhasSelect; ?>" />

        <!--<input type="hidden" name="num_linhas_url" id="num_linhas_url" value="<?php //echo $this->numLinhasSelect; ?>" />-->
        <select class="pagesize" style="width: 70px" id="num_pagina_select" name="num_linhas_select">
            <option value="15" <?php if($this->numLinhasSelect == 15){ echo " selected"; } ?>>15</option>
            <option value="50" <?php if($this->numLinhasSelect == 50){ echo " selected"; } ?>>50</option>
            <option value="100" <?php if($this->numLinhasSelect == 100){ echo " selected"; } ?>>100</option>
        </select>
    </form>
</div>

<script type="text/javascript">
    function trocaOrdem(asc_desc){
        if(asc_desc === "asc"){
            asc_desc = "desc";
        }else if(asc_desc === "desc"){
            asc_desc = "asc";
        }

        return asc_desc;
    }

    $(document).ready(function() {
        $("#1").click(function () {
            var asc_desc = $("#nr_chamado_asc_desc").val();
            var ordem = trocaOrdem(asc_desc);

            $(location).attr('href', '/manutencao/modulo/listar/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porProjeto/<?php echo $this->porProjeto; ?>/pg/<?php echo $this->pg; ?>/coluna/1/ordem/' + ordem);
        })

        $("#2").click(function () {
            var asc_desc = $("#nr_chamado_asc_desc").val();
            var ordem = trocaOrdem(asc_desc);

            $(location).attr('href', '/manutencao/modulo/listar/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porProjeto/<?php echo $this->porProjeto; ?>/pg/<?php echo $this->pg; ?>/coluna/2/ordem/' + ordem);
        })

        $("#3").click(function () {
            var asc_desc = $("#nr_chamado_asc_desc").val();
            var ordem = trocaOrdem(asc_desc);

            $(location).attr('href', '/manutencao/modulo/listar/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porProjeto/<?php echo $this->porProjeto; ?>/pg/<?php echo $this->pg; ?>/coluna/3/ordem/' + ordem);
        })
    });
</script>

<input type="hidden" id="nr_chamado_asc_desc" name="nr_chamado_asc_desc" value="<?php echo $this->ordem; ?>">

<div class="">
    <div class="row-fluid">
        <?php $this->mensagem(); ?>
        <div class="">
        <div class="widget-box">
          <div class="widget-title">
             
            <h5> <i class="icon-list-alt"></i> Lista de Módulos</h5>
          </div>
            <div class="widget-content nopadding">
            <input type="hidden" name="totalrecords" id="totalrecords" value="<?php echo $this->oTotal; ?>" />

                <?php if(CO_PERFIL == 1) { ?>

                    <table class="table table-bordered table-striped table-condensed" id="mt">
                        <thead>
                            <tr>
                               <!-- <th>input type="checkbox" class="check-all"></th> -->
                                <th id="1" style="cursor: pointer" class="span3">Nome
                                    <?php
                                    if ($this->coluna == 1) {
                                        if ($this->ordem == "asc") {
                                            echo "<img src='/images/sort_desc.png'>";
                                        } else {
                                            echo "<img src='/images/sort_asc.png'>";
                                        }
                                    } else {
                                        echo "<img src='/images/sort_both.png'>";
                                    }
                                    ?>
                                </th>
                                <th id="2" style="cursor: pointer" class="span3">Projeto
                                    <?php
                                    if ($this->coluna == 2) {
                                        if ($this->ordem == "asc") {
                                            echo "<img src='/images/sort_desc.png'>";
                                        } else {
                                            echo "<img src='/images/sort_asc.png'>";
                                        }
                                    } else {
                                        echo "<img src='/images/sort_both.png'>";
                                    }
                                    ?>
                                </th>
                                <th id="3" style="cursor: pointer" class="span4">Descrição
                                    <?php
                                    if ($this->coluna == 3) {
                                        if ($this->ordem == "asc") {
                                            echo "<img src='/images/sort_desc.png'>";
                                        } else {
                                            echo "<img src='/images/sort_asc.png'>";
                                        }
                                    } else {
                                        echo "<img src='/images/sort_both.png'>";
                                    }
                                    ?>
                                </th>
                                <th class="span2">Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0;
                            foreach ($this->aObjModulo as $objModulo) { ?>
                                <tr <?php if (($i % 2) == 0) { ?> class="alt-row" <?php } ?> >
                                    <td><?php print $objModulo->getNoModulo(); ?></td>
                                    <td><?php print $objModulo->getProjeto()->getNoProjeto(); ?></td>
                                    <td><?php print $objModulo->getDsModulo(); ?></td>
                                    <td>
                                        <!-- Icons -->
                                        <div class="btn-group">
                                            <?php if($objModulo->getStModulo()){ ?>
                                                <a title="Editar" href="/manutencao/modulo/adicionar/co_modulo/<?php echo $objModulo->getCoSeqModuloProj(); ?>/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porProjeto/<?php echo $this->porProjeto; ?>/coluna/<?php echo $this->coluna; ?>/ordem/<?php echo $this->ordem; ?>/pg/<?php echo $this->pg; ?>" class="btn btn-small"><i class="icon-edit"></i></a>
                                                <a title="Excluir" href="javascript:if (confirm('Deseja realmente desativar este Módulo?')) window.location = '/manutencao/modulo/excluir/co_modulo/<?php echo $objModulo->getCoSeqModuloProj(); ?>'; " class="btn btn-small"><i class="icon-remove"></i></a>
                                            <?php } else {?>
                                                <a title="Ativar" href="javascript:if (confirm('Deseja realmente ativar este Módulo?')) window.location = '/manutencao/modulo/ativar/co_modulo/<?php echo $objModulo->getCoSeqModuloProj(); ?>'; " class="btn btn-small"><i class="icon-ok"></i></a>
                                            <?php }?>

                                        </div>
                                    </td>
                                </tr>
                            <?php $i++; } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="18" style="font-weight: bold">
                                <div class="pull-right">Total de Registros: <?php echo $this->oTotal == '' ? count($this->oTarefa) : $this->oTotal;?></div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>

                <?php } else { ?>

                    <table class="table table-bordered table-striped" id="mt">
                        <thead>
                        <tr>
                            <!-- <th>input type="checkbox" class="check-all"></th> -->
                            <th id="1" style="cursor: pointer" class="span3">Nome
                                <?php
                                if ($this->coluna == 1) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                            <th id="2" style="cursor: pointer" class="span3">Projeto
                                <?php
                                if ($this->coluna == 1) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                            <th id="3" style="cursor: pointer" class="span4">Descrição
                                <?php
                                if ($this->coluna == 1) {
                                    if ($this->ordem == "asc") {
                                        echo "<img src='/images/sort_desc.png'>";
                                    } else {
                                        echo "<img src='/images/sort_asc.png'>";
                                    }
                                } else {
                                    echo "<img src='/images/sort_both.png'>";
                                }
                                ?>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0;
                        foreach ($this->aObjModulo as $objModulo) { ?>
                            <tr <?php if (($i % 2) == 0) { ?> class="alt-row" <?php } ?> >
                                <td><?php print $objModulo->getNoModulo(); ?></td>
                                <td><?php print $objModulo->getProjeto()->getNoProjeto(); ?></td>
                                <td><?php print $objModulo->getDsModulo(); ?></td>
                            </tr>
                            <?php $i++; } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="18" style="font-weight: bold">
                                <div class="pull-right">Total de Registros: <?php echo $this->oTotal == '' ? count($this->oTarefa) : $this->oTotal;?></div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>

                <?php } ?>

                <div class="pagination pagination-centered">
                    <ul>
                        <?php echo $this->pagination; ?>
                    </ul>
                </div>

                <!--
                    <div id="paginacao" style="margin: auto;">
                    </div>
                -->

        </div> <!-- End #tab2 -->
        <br />
        <?php if(CO_PERFIL == 1) { ?>
   		<div class="row-fluid">
            <div class="span12">
                <div class="form-actions">
                    <a class="btn btn-primary" href="/manutencao/modulo/adicionar/num_linhas/<?php echo $this->numLinhasSelect; ?>/tipoBusca/<?php echo $this->tipoBusca; ?>/porNome/<?php echo $this->porNome; ?>/porProjeto/<?php echo $this->porProjeto; ?>/coluna/<?php echo $this->coluna; ?>/ordem/<?php echo $this->ordem; ?>/pg/<?php echo $this->pg; ?>">Cadastrar</a>
                </div>
            </div>
    	</div>
        <?php } ?>
    </div>
  
</div> <!-- End BOX GERAL GRID--> 
<!-- END BOX CRUD --> 
</div>
</div>

